name: Deploy

on: push

env:
  STACK_NAME: deploy-test-project

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  delete-stack:
    runs-on: ubuntu-latest
    needs: checkout
    use: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2
    steps:
      - name: delete stack
        run: |
          aws cloudformation delete-stack --stack-name $STACK_NAME

  create-stack:
    needs: delete-stack
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2
    runs-on: ubuntu-latest
    steps:
      - name: create VPC and networking
        run: |
          aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://networkcfn.yml  --parameters file://network-params.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2

  update-stack:
    needs: create-stack
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2
    runs-on: ubuntu-latest
    steps:
      - name: create server
        run: |
          aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://servercfn.yml  --parameters file://server-params.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2
