name: Deploy

on: push

env:
  STACK_NAME: deploy-test-project

jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  delete-stack:
    runs-on: ubuntu-latest
    needs: checkout-actions
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: delete stack
        run: |
          aws cloudformation delete-stack --stack-name $STACK_NAME

  create-stack:
    runs-on: ubuntu-latest
    needs: delete-stack
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: create VPC and networking
        working-directory: ./
        run: |
          aws cloudformation create-stack --stack-name deploy-test-project --template-body file:///networkcfn.yml  --parameters file:///network-params.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2

  update-stack:
    runs-on: ubuntu-latest
    needs: create-stack
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: create server
        working-directory: ./
        run: |
          aws cloudformation update-stack --stack-name deploy-test-project --template-body file:///servercfn.yml  --parameters file:///server-params.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2
