name: Deploy

on: push

env:
  STACK_NAME: deploy-test-project

jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  delete-stack:
    runs-on: ubuntu-latest
    needs: checkout-actions
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: delete stack
        run: |
          aws cloudformation delete-stack --stack-name $STACK_NAME

  create-stack:
    runs-on: ubuntu-latest
    needs: delete-stack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: create VPC and networking
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: $STACK_NAME
          template: ../networkcfn.yml
          parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
  
  update-stack:
    runs-on: ubuntu-latest
    needs: create-stack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: create server
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: $STACK_NAME
          template: servercfn.yml
          parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
